name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.5.2

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Micropython cross
        run: make -C micropython/mpy-cross

      - name: Build
        run: |
          . $IDF_PATH/export.sh
          BOARD_DIR=`pwd`/boards/SEEED_XIAO_EE02
          cd micropython/ports/esp32
          make BOARD_DIR=$BOARD_DIR submodules
          make BOARD_DIR=$BOARD_DIR FROZEN_MANIFEST=$MANIFEST
          cd build-SEEED_XIAO_EE02
          python -m esptool --chip esp32s3 merge_bin -o firmware.bin "@flash_args"
          
      - name: Upload Firmware
        uses: actions/upload-artifact@v7
        with:
          name: ee02-firmware.bin
          archive: false
          path: micropython/ports/esp32/build-SEEED_XIAO_EE02/firmware.bin 

      - name: Upload OTA
        uses: actions/upload-artifact@v7
        with:
          name: ee02-ota.app-bin
          archive: false
          path: micropython/ports/esp32/build-SEEED_XIAO_EE02/micropython.bin 
 
